/**
 * Lista de países em português (PT-PT), ordenada alfabeticamente.
 * Inclui PALOP, Europa, Américas, África e Ásia (alargada).
 * Usar para inputs de "País" / "País de Emissão" / "Naturalidade".
 */
export const PAISES = [
  'Afeganistão',
  'África do Sul',
  'Albânia',
  'Alemanha',
  'Andorra',
  'Angola',
  'Arábia Saudita',
  'Argélia',
  'Argentina',
  'Austrália',
  'Áustria',
  'Bélgica',
  'Bolívia',
  'Bósnia e Herzegovina',
  'Brasil',
  'Bulgária',
  'Cabo Verde',
  'Camarões',
  'Canadá',
  'Cazaquistão',
  'Chile',
  'China',
  'Chipre',
  'Colômbia',
  'Coreia do Sul',
  'Costa do Marfim',
  'Costa Rica',
  'Croácia',
  'Cuba',
  'Dinamarca',
  'Egito',
  'El Salvador',
  'Emirados Árabes Unidos',
  'Equador',
  'Eslováquia',
  'Eslovénia',
  'Espanha',
  'Estados Unidos',
  'Estónia',
  'Etiópia',
  'Filipinas',
  'Finlândia',
  'França',
  'Gana',
  'Geórgia',
  'Grécia',
  'Guatemala',
  'Guiné',
  'Guiné-Bissau',
  'Guiné Equatorial',
  'Haiti',
  'Honduras',
  'Hungria',
  'Iémen',
  'Índia',
  'Indonésia',
  'Irão',
  'Iraque',
  'Irlanda',
  'Islândia',
  'Israel',
  'Itália',
  'Japão',
  'Jordânia',
  'Kuwait',
  'Letónia',
  'Líbano',
  'Líbia',
  'Liechtenstein',
  'Lituânia',
  'Luxemburgo',
  'Macedónia do Norte',
  'Madagáscar',
  'Malásia',
  'Mali',
  'Malta',
  'Marrocos',
  'México',
  'Moldávia',
  'Mónaco',
  'Moçambique',
  'Montenegro',
  'Nicarágua',
  'Nigéria',
  'Noruega',
  'Nova Zelândia',
  'Países Baixos',
  'Paquistão',
  'Panamá',
  'Paraguai',
  'Peru',
  'Polónia',
  'Portugal',
  'Qatar',
  'Quénia',
  'Reino Unido',
  'República Centro-Africana',
  'República Checa',
  'República Democrática do Congo',
  'República Dominicana',
  'Roménia',
  'Ruanda',
  'Rússia',
  'Sahara Ocidental',
  'San Marino',
  'Senegal',
  'Sérvia',
  'Singapura',
  'Síria',
  'Sri Lanka',
  'Sudão',
  'Suécia',
  'Suíça',
  'Tailândia',
  'Taiwan',
  'Tanzânia',
  'Timor-Leste',
  'Togo',
  'Tunísia',
  'Turquia',
  'Ucrânia',
  'Uganda',
  'Uruguai',
  'Vaticano',
  'Venezuela',
  'Vietname',
  'Zâmbia',
  'Zimbabué',
  'São Tomé e Príncipe',
] as const;

export type Pais = (typeof PAISES)[number];
