export type Motorista = {
  id: string;
  codigo: number;
  nome: string;
  nif: string | null;
  documento_tipo: string | null;
  documento_numero: string | null;
  documento_validade: string | null;
  documento_ficheiro_url?: string | null;
  documento_identificacao_verso_url?: string | null;
  carta_conducao: string | null;
  carta_categorias: string[] | null;
  carta_validade: string | null;
  carta_ficheiro_url?: string | null;
  carta_conducao_verso_url?: string | null;
  licenca_tvde_numero: string | null;
  licenca_tvde_validade: string | null;
  licenca_tvde_ficheiro_url?: string | null;
  registo_criminal_url?: string | null;
  comprovativo_morada_url?: string | null;
  comprovativo_iban_url?: string | null;
  morada: string | null;
  codigo_postal: string | null;
  email: string | null;
  telefone: string | null;
  data_contratacao: string | null;
  data_renovacao_contratacao: string | null;
  cidade: string | null;
  cidade_assinatura: string | null;
  status_ativo: boolean | null;
  recibo_verde: boolean | null;
  is_slot: boolean | null;
  slot_valor_semanal: number | null;
  cartao_frota: string | null;
  cartao_bp: string | null;
  cartao_repsol: string | null;
  cartao_edp: string | null;
  iban: string | null;
  observacoes: string | null;
  uber_uuid: string | null;
  bolt_id: string | null;
  gestor_responsavel: string | null;
  created_at: string;
  updated_at: string;
};
