-- ============================================================
-- Contratos de Prestação de Serviços (regime SLOT)
-- ============================================================
-- No regime slot o motorista usa carro próprio e paga semanalmente para
-- trabalhar como TVDE sob a licença da empresa. O vínculo legal é este
-- contrato de prestação de serviços (NÃO um contrato de aluguer).
--
-- Tabela nova, org-isolada desde o início (multi-tenant SaaS) — ao
-- contrário da legacy `contratos` que tem CHECK hardcoded de empresa.
-- Idempotente. RLS espelha contratos_renting (permissão renting_contratos).
-- ============================================================

CREATE TABLE IF NOT EXISTS public.contratos_prestacao (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id          uuid NOT NULL DEFAULT public.get_current_org_id()
                    REFERENCES public.organizacoes(id) ON DELETE CASCADE,
  codigo          bigint GENERATED BY DEFAULT AS IDENTITY,

  motorista_id    uuid NOT NULL REFERENCES public.motoristas_ativos(id) ON DELETE RESTRICT,
  viatura_id      uuid REFERENCES public.viaturas(id) ON DELETE SET NULL,
  reserva_id      uuid REFERENCES public.reservas(id) ON DELETE SET NULL,

  data_inicio     date NOT NULL DEFAULT CURRENT_DATE,
  data_fim        date,                          -- NULL = aberto (slot recorrente)
  valor_semanal   numeric(10,2),                 -- cobrado por carro
  estado          text NOT NULL DEFAULT 'ativo', -- 'ativo' | 'encerrado'

  -- Snapshot do motorista no momento da assinatura (estabilidade legal)
  motorista_nome      text,
  motorista_nif       text,
  motorista_morada    text,
  motorista_email     text,
  motorista_telefone  text,

  documento_url   text,        -- PDF gerado (storage), opcional
  versao          integer NOT NULL DEFAULT 1,
  observacoes     text,

  deleted_at      timestamptz,
  created_by      uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by      uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT contratos_prestacao_estado_chk CHECK (estado IN ('ativo', 'encerrado'))
);

CREATE INDEX IF NOT EXISTS idx_contratos_prestacao_org ON public.contratos_prestacao(org_id);
CREATE INDEX IF NOT EXISTS idx_contratos_prestacao_motorista ON public.contratos_prestacao(motorista_id);
CREATE INDEX IF NOT EXISTS idx_contratos_prestacao_reserva ON public.contratos_prestacao(reserva_id);

-- updated_at automático (reusa trigger genérico se existir; senão cria)
CREATE OR REPLACE FUNCTION public.fn_contratos_prestacao_touch()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_contratos_prestacao_touch ON public.contratos_prestacao;
CREATE TRIGGER trg_contratos_prestacao_touch
  BEFORE UPDATE ON public.contratos_prestacao
  FOR EACH ROW EXECUTE FUNCTION public.fn_contratos_prestacao_touch();

-- ────────────────────────────────────────────────────────────
-- RLS — espelha contratos_renting (permissão renting_contratos)
-- ────────────────────────────────────────────────────────────
ALTER TABLE public.contratos_prestacao ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "contratos_prestacao_select" ON public.contratos_prestacao;
CREATE POLICY "contratos_prestacao_select" ON public.contratos_prestacao
FOR SELECT TO authenticated
USING (
  org_id = public.get_current_org_id()
  AND public.has_renting_contratos_access()
  AND (deleted_at IS NULL OR public.is_current_user_admin())
);

DROP POLICY IF EXISTS "contratos_prestacao_insert" ON public.contratos_prestacao;
CREATE POLICY "contratos_prestacao_insert" ON public.contratos_prestacao
FOR INSERT TO authenticated
WITH CHECK (
  org_id = public.get_current_org_id()
  AND public.has_renting_contratos_access()
  AND deleted_at IS NULL
);

DROP POLICY IF EXISTS "contratos_prestacao_update" ON public.contratos_prestacao;
CREATE POLICY "contratos_prestacao_update" ON public.contratos_prestacao
FOR UPDATE TO authenticated
USING (
  org_id = public.get_current_org_id()
  AND public.has_renting_contratos_access()
  AND (deleted_at IS NULL OR public.is_current_user_admin())
)
WITH CHECK (
  org_id = public.get_current_org_id()
  AND public.has_renting_contratos_access()
);

DROP POLICY IF EXISTS "contratos_prestacao_delete" ON public.contratos_prestacao;
CREATE POLICY "contratos_prestacao_delete" ON public.contratos_prestacao
FOR DELETE TO authenticated
USING (
  org_id = public.get_current_org_id()
  AND public.is_current_user_admin()
);

-- Política RESTRICTIVE de isolamento multi-tenant (rls_org_isolation)
DROP POLICY IF EXISTS "rls_org_isolation" ON public.contratos_prestacao;
CREATE POLICY "rls_org_isolation" ON public.contratos_prestacao
AS RESTRICTIVE FOR ALL TO authenticated
USING (org_id = public.get_current_org_id())
WITH CHECK (org_id IS NULL OR org_id = public.get_current_org_id());
