-- ============================================================
-- Migration: contratos (renting) — MVP
-- ============================================================
-- Tabela `contratos` com:
--   • Multi-tenancy via org_id
--   • Ligação opcional a reserva (walk-ins suportados)
--   • Anti-overbooking via EXCLUDE USING gist + tstzrange
--   • Estados em 2 dimensões (operacional + financeiro)
--   • Snapshot de totais para imutabilidade fiscal após facturação
--   • Soft delete + RLS + auditoria
--
-- Estados:
--   estado_operacional: 'agendado' → 'em_curso' → 'devolvido' + 'cancelado'
--   estado_financeiro:  'pendente' → 'facturado' → 'pago' + 'anulado'
--
-- Decisões deliberadas (NÃO adicionar sem necessidade real):
--   • SEM ALD agora (vai para `contrato_series` quando implementado)
--   • SEM snapshot cliente_nome (FK RESTRICT garante FK válida)
--   • SEM flags activar_franquia_manual / activar_limite_kms_manual (são UI)
--   • SEM multi-cobertura (FK única `cobertura_id` chega no MVP)
--   • SEM pacotes, taxas, extras (sprints futuros)
-- ============================================================


-- ============================================================
-- ENUMs
-- ============================================================
DO $$ BEGIN
  CREATE TYPE public.contrato_estado_operacional_enum AS ENUM (
    'agendado',   -- criado, viatura ainda não entregue ao cliente
    'em_curso',   -- viatura entregue, contrato activo
    'devolvido',  -- viatura devolvida, contrato fechado
    'cancelado'   -- anulado antes de produzir efeitos
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE public.contrato_estado_financeiro_enum AS ENUM (
    'pendente',    -- ainda não facturado
    'facturado',   -- factura emitida (totais congelados)
    'pago',        -- factura liquidada
    'anulado'      -- factura anulada (volta a pendente conceptualmente)
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE public.contrato_origem_enum AS ENUM (
    'sistema',
    'online',
    'telefone',
    'balcao'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;


-- ============================================================
-- Helper RBAC
-- ============================================================
CREATE OR REPLACE FUNCTION public.has_renting_contratos_access()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
  SELECT is_current_user_admin()
  OR has_permission(auth.uid(), 'renting_contratos');
$$;


-- ============================================================
-- CONTRATOS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.contratos_renting (
  id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  org_id                      UUID NOT NULL REFERENCES public.organizacoes(id) ON DELETE CASCADE
                              DEFAULT public.get_current_org_id(),

  codigo                      BIGINT GENERATED BY DEFAULT AS IDENTITY,

  -- Ligação opcional a reserva. UNIQUE — uma reserva = no máximo 1 contrato.
  reserva_id                  UUID UNIQUE REFERENCES public.reservas(id) ON DELETE SET NULL,

  -- Cliente (obrigatório, sem snapshot — FK RESTRICT garante validade)
  cliente_id                  UUID NOT NULL REFERENCES public.clientes(id) ON DELETE RESTRICT,

  -- Viatura (obrigatória; snapshot matrícula porque viatura pode mudar matrícula com o tempo)
  viatura_id                  UUID NOT NULL REFERENCES public.viaturas(id) ON DELETE RESTRICT,
  matricula                   VARCHAR(20),   -- snapshot histórico
  grupo                       VARCHAR(50),   -- texto livre (categoria visual)

  -- Entrega
  estacao_entrega_id          UUID REFERENCES public.estacoes(id) ON DELETE SET NULL,
  data_inicio                 TIMESTAMPTZ NOT NULL,

  -- Recolha
  estacao_recolha_id          UUID REFERENCES public.estacoes(id) ON DELETE SET NULL,
  data_fim                    TIMESTAMPTZ NOT NULL,

  -- Estação ORIGEM da viatura (de onde sai fisicamente)
  estacao_origem_viatura_id   UUID REFERENCES public.estacoes(id) ON DELETE SET NULL,

  -- Estados (2 dimensões)
  estado_operacional          public.contrato_estado_operacional_enum NOT NULL DEFAULT 'agendado',
  estado_financeiro           public.contrato_estado_financeiro_enum NOT NULL DEFAULT 'pendente',

  origem                      public.contrato_origem_enum NOT NULL DEFAULT 'sistema',

  -- Tarifário (MVP — manual; v2 ligará a tabela `tarifas`)
  tarifa_diaria               NUMERIC(10, 2),
  desconto_percentagem        NUMERIC(5, 2) DEFAULT 0,
  taxa_iva                    NUMERIC(5, 2) NOT NULL DEFAULT 23,
  valor_total_manual          NUMERIC(10, 2),  -- override directo do total (bypass cálculo)

  -- Snapshot de totais — congelados quando estado_financeiro = 'facturado'
  -- NULL enquanto pendente. Imutáveis após facturação (compliance SAF-T).
  total_subtotal              NUMERIC(10, 2),
  total_iva                   NUMERIC(10, 2),
  total_final                 NUMERIC(10, 2),
  facturado_em                TIMESTAMPTZ,

  -- Voucher
  voucher_codigo              VARCHAR(50),

  -- Informação adicional
  numero_processo             VARCHAR(100),
  voo_referencia              VARCHAR(100),     -- ex.: "TP1234 chegada / TP5678 partida"
  local_entrega               VARCHAR(255),
  local_recolha               VARCHAR(255),
  comentarios_entrega         TEXT,
  comentarios_recolha         TEXT,

  observacoes                 TEXT,

  -- Soft delete
  deleted_at                  TIMESTAMPTZ,

  -- Auditoria
  created_by                  UUID REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  updated_by                  UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at                  TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),

  -- Coluna gerada (base do EXCLUDE)
  periodo                     TSTZRANGE GENERATED ALWAYS AS (
                                tstzrange(data_inicio, data_fim, '[)')
                              ) STORED,

  CONSTRAINT chk_contratos_periodo_valido CHECK (data_fim > data_inicio),
  CONSTRAINT chk_contratos_iva_valido CHECK (taxa_iva >= 0 AND taxa_iva <= 100),
  CONSTRAINT chk_contratos_desconto_valido CHECK (
    desconto_percentagem IS NULL OR (desconto_percentagem >= 0 AND desconto_percentagem <= 100)
  ),
  CONSTRAINT chk_contratos_totais_facturados CHECK (
    -- Se facturado, totais e data de facturação devem estar preenchidos
    estado_financeiro <> 'facturado'
    OR (total_final IS NOT NULL AND facturado_em IS NOT NULL)
  ),
  CONSTRAINT contratos_renting_codigo_org_unique UNIQUE (org_id, codigo)
);

COMMENT ON COLUMN public.contratos_renting.reserva_id IS
  'FK opcional à reserva de origem. UNIQUE — 1 reserva = 1 contrato. NULL para walk-ins.';

COMMENT ON COLUMN public.contratos_renting.matricula IS
  'Snapshot da matrícula no momento do contrato. Viatura pode mudar matrícula (legalmente raro mas possível).';

COMMENT ON COLUMN public.contratos_renting.estado_operacional IS
  'Ciclo físico: agendado → em_curso → devolvido. cancelado é terminal.';

COMMENT ON COLUMN public.contratos_renting.estado_financeiro IS
  'Ciclo de facturação: pendente → facturado → pago. anulado retorna a fluxo.';

COMMENT ON COLUMN public.contratos_renting.total_final IS
  'Snapshot do total facturado. NULL enquanto estado_financeiro=pendente. '
  'Congelado quando muda para facturado (compliance SAF-T — não altera retroactivamente).';

COMMENT ON COLUMN public.contratos_renting.periodo IS
  'Coluna GENERATED ALWAYS — NÃO escrever manualmente. Base do EXCLUDE anti-overbooking.';


-- ============================================================
-- Anti-overbooking: viatura não pode estar em 2 contratos activos sobrepostos
-- Activo = estado_operacional IN ('agendado', 'em_curso')
-- ============================================================
DO $$ BEGIN
  ALTER TABLE public.contratos_renting
    ADD CONSTRAINT contratos_no_overbooking
    EXCLUDE USING gist (
      org_id     WITH =,
      viatura_id WITH =,
      periodo    WITH &&
    ) WHERE (
      deleted_at IS NULL
      AND estado_operacional IN ('agendado', 'em_curso')
    );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;


-- ============================================================
-- Trigger cross-table: contrato não pode ser criado se houver
-- reserva activa sobreposta para a mesma viatura (excepto se reserva_id
-- aponta exactamente para essa reserva — caso reserva→contrato).
-- ============================================================
CREATE OR REPLACE FUNCTION public.fn_contratos_validar_reserva()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.viatura_id IS NULL OR NEW.deleted_at IS NOT NULL THEN
    RETURN NEW;
  END IF;

  -- Estados activos do contrato bloqueiam
  IF NEW.estado_operacional NOT IN ('agendado', 'em_curso') THEN
    RETURN NEW;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.reservas r
    WHERE r.org_id = NEW.org_id
      AND r.viatura_id = NEW.viatura_id
      AND r.deleted_at IS NULL
      AND r.estado IN ('pendente', 'confirmada', 'em_curso')
      AND r.periodo && NEW.periodo
      -- Excepção: reserva que ORIGINOU este contrato não conflita consigo mesma
      AND (NEW.reserva_id IS NULL OR r.id <> NEW.reserva_id)
  ) THEN
    RAISE EXCEPTION
      'Conflito: viatura já tem reserva activa sobreposta para este período.'
      USING ERRCODE = 'exclusion_violation';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_contratos_renting_validar_reserva ON public.contratos_renting;
CREATE TRIGGER trg_contratos_renting_validar_reserva
BEFORE INSERT OR UPDATE OF viatura_id, data_inicio, data_fim, estado_operacional, deleted_at
ON public.contratos_renting
FOR EACH ROW EXECUTE FUNCTION public.fn_contratos_validar_reserva();


-- ============================================================
-- Índices
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_contratos_renting_timeline
  ON public.contratos_renting (org_id, viatura_id, data_inicio, data_fim)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_contratos_renting_cliente
  ON public.contratos_renting (org_id, cliente_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_contratos_renting_reserva
  ON public.contratos_renting (reserva_id)
  WHERE reserva_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_contratos_renting_data_inicio
  ON public.contratos_renting (org_id, data_inicio DESC) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_contratos_renting_estado_op
  ON public.contratos_renting (org_id, estado_operacional) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_contratos_renting_estado_fin
  ON public.contratos_renting (org_id, estado_financeiro) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_contratos_renting_matricula
  ON public.contratos_renting (org_id, matricula)
  WHERE matricula IS NOT NULL AND deleted_at IS NULL;

-- Gist para overlap queries
CREATE INDEX IF NOT EXISTS idx_contratos_renting_periodo_active
  ON public.contratos_renting USING gist (org_id, viatura_id, periodo)
  WHERE deleted_at IS NULL AND estado_operacional IN ('agendado', 'em_curso');


-- ============================================================
-- Auditoria automática (reusa fn_audit_update existente)
-- ============================================================
DROP TRIGGER IF EXISTS trg_contratos_renting_audit ON public.contratos_renting;
CREATE TRIGGER trg_contratos_renting_audit
BEFORE UPDATE ON public.contratos_renting
FOR EACH ROW EXECUTE FUNCTION public.fn_audit_update();


-- ============================================================
-- RLS
-- ============================================================
ALTER TABLE public.contratos_renting ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "contratos_renting_select" ON public.contratos_renting;
CREATE POLICY "contratos_renting_select" ON public.contratos_renting
FOR SELECT TO authenticated
USING (
  org_id = public.get_current_org_id()
  AND public.has_renting_contratos_access()
  AND (deleted_at IS NULL OR public.is_current_user_admin())
);

DROP POLICY IF EXISTS "contratos_renting_insert" ON public.contratos_renting;
CREATE POLICY "contratos_renting_insert" ON public.contratos_renting
FOR INSERT TO authenticated
WITH CHECK (
  org_id = public.get_current_org_id()
  AND public.has_renting_contratos_access()
  AND deleted_at IS NULL
);

DROP POLICY IF EXISTS "contratos_renting_update" ON public.contratos_renting;
CREATE POLICY "contratos_renting_update" ON public.contratos_renting
FOR UPDATE TO authenticated
USING (
  org_id = public.get_current_org_id()
  AND public.has_renting_contratos_access()
  AND (deleted_at IS NULL OR public.is_current_user_admin())
)
WITH CHECK (
  org_id = public.get_current_org_id()
  AND public.has_renting_contratos_access()
);

DROP POLICY IF EXISTS "contratos_renting_delete" ON public.contratos_renting;
CREATE POLICY "contratos_renting_delete" ON public.contratos_renting
FOR DELETE TO authenticated
USING (
  org_id = public.get_current_org_id()
  AND public.is_current_user_admin()
);


-- ============================================================
-- RPC: detectar conflito de datas para UX
-- Verifica conflitos com contratos E reservas (cross-table)
-- ============================================================
CREATE OR REPLACE FUNCTION public.contrato_tem_conflito(
  p_viatura_id   UUID,
  p_data_inicio  TIMESTAMPTZ,
  p_data_fim     TIMESTAMPTZ,
  p_excluir_id   UUID DEFAULT NULL,
  p_reserva_id   UUID DEFAULT NULL
) RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT EXISTS (
    -- Outros contratos activos
    SELECT 1 FROM public.contratos_renting
    WHERE org_id = public.get_current_org_id()
      AND viatura_id = p_viatura_id
      AND deleted_at IS NULL
      AND estado_operacional IN ('agendado', 'em_curso')
      AND periodo && tstzrange(p_data_inicio, p_data_fim, '[)')
      AND (p_excluir_id IS NULL OR id <> p_excluir_id)
    UNION ALL
    -- Reservas activas (excepto a que originou este contrato)
    SELECT 1 FROM public.reservas
    WHERE org_id = public.get_current_org_id()
      AND viatura_id = p_viatura_id
      AND deleted_at IS NULL
      AND estado IN ('pendente', 'confirmada', 'em_curso')
      AND periodo && tstzrange(p_data_inicio, p_data_fim, '[)')
      AND (p_reserva_id IS NULL OR id <> p_reserva_id)
  );
$$;

GRANT EXECUTE ON FUNCTION public.contrato_tem_conflito(UUID, TIMESTAMPTZ, TIMESTAMPTZ, UUID, UUID)
  TO authenticated;
