-- ============================================================
-- M4 — Conta-corrente local: `recibos` + `conta_movimentos`
-- ============================================================
-- Cada entidade (cliente OU condutor — todos são clientes) tem
-- a sua conta-corrente, INDEPENDENTE das outras.
--
--   • conta_movimentos — livro razão (append-only). Cada linha é
--     um débito ou um crédito. Saldo = Σ débitos − Σ créditos.
--   • recibos          — pagamentos recebidos (geram créditos).
--   • contrato_cobrancas (M3) — ao emitir, gera um débito.
--
-- Funciona sozinho; os campos `*_primavera` ficam prontos para
-- sincronizar com o ERP quando a integração arrancar.
-- ============================================================

-- Helper de acesso à faturação/financeiro do renting
CREATE OR REPLACE FUNCTION public.has_renting_faturacao_access()
RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT is_current_user_admin()
      OR has_permission(auth.uid(), 'renting_contratos')
      OR has_permission(auth.uid(), 'financeiro_recibos');
$$;

-- ============================================================
-- RECIBOS — pagamentos recebidos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.recibos (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id          uuid NOT NULL REFERENCES public.organizacoes(id) ON DELETE CASCADE,
  codigo          bigint GENERATED BY DEFAULT AS IDENTITY,

  -- A quem pertence o crédito (cliente ou condutor)
  entidade_id     uuid NOT NULL REFERENCES public.clientes(id) ON DELETE RESTRICT,
  -- Contexto opcional
  contrato_id     uuid REFERENCES public.contratos_renting(id) ON DELETE SET NULL,

  valor           numeric(10,2) NOT NULL CHECK (valor > 0),
  data_recibo     date NOT NULL DEFAULT current_date,
  metodo          text CHECK (metodo IN
                    ('numerario','transferencia','mbway','multibanco','cheque','outro')),
  referencia      text,
  observacoes     text,

  estado          text NOT NULL DEFAULT 'ativo' CHECK (estado IN ('ativo','anulado')),

  -- Sincronização Primavera
  documento_externo_ref   text,
  sincronizado_primavera  boolean NOT NULL DEFAULT false,

  created_by      uuid REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT recibos_codigo_org_unique UNIQUE (org_id, codigo)
);

CREATE INDEX IF NOT EXISTS idx_recibos_org       ON public.recibos (org_id);
CREATE INDEX IF NOT EXISTS idx_recibos_entidade  ON public.recibos (entidade_id);
CREATE INDEX IF NOT EXISTS idx_recibos_contrato  ON public.recibos (contrato_id) WHERE contrato_id IS NOT NULL;

-- ============================================================
-- CONTA_MOVIMENTOS — livro razão (append-only)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.conta_movimentos (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id          uuid NOT NULL REFERENCES public.organizacoes(id) ON DELETE CASCADE,

  -- Conta-corrente de quem
  entidade_id     uuid NOT NULL REFERENCES public.clientes(id) ON DELETE RESTRICT,

  data_movimento  date NOT NULL DEFAULT current_date,
  tipo            text NOT NULL CHECK (tipo IN ('debito','credito')),
  valor           numeric(10,2) NOT NULL CHECK (valor > 0),

  -- O que originou o movimento
  origem          text NOT NULL CHECK (origem IN ('cobranca','recibo','dano','ajuste')),
  cobranca_id     uuid REFERENCES public.contrato_cobrancas(id) ON DELETE SET NULL,
  recibo_id       uuid REFERENCES public.recibos(id)            ON DELETE SET NULL,
  contrato_id     uuid REFERENCES public.contratos_renting(id)  ON DELETE SET NULL,
  descricao       text,

  -- Sincronização Primavera
  sincronizado_primavera  boolean NOT NULL DEFAULT false,
  primavera_ref           text,

  created_by      uuid REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_conta_movimentos_entidade
  ON public.conta_movimentos (org_id, entidade_id, data_movimento);
CREATE INDEX IF NOT EXISTS idx_conta_movimentos_cobranca
  ON public.conta_movimentos (cobranca_id) WHERE cobranca_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_conta_movimentos_recibo
  ON public.conta_movimentos (recibo_id) WHERE recibo_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_conta_movimentos_por_sincronizar
  ON public.conta_movimentos (org_id) WHERE sincronizado_primavera = false;

-- ============================================================
-- Saldo da conta-corrente de uma entidade
-- Convenção: positivo = a entidade DEVE; negativo = tem crédito a favor.
-- ============================================================
CREATE OR REPLACE FUNCTION public.conta_corrente_saldo(p_entidade_id uuid)
RETURNS numeric
LANGUAGE sql STABLE SECURITY INVOKER
SET search_path = public
AS $$
  SELECT COALESCE(SUM(
    CASE tipo WHEN 'debito' THEN valor ELSE -valor END
  ), 0)::numeric(12,2)
  FROM public.conta_movimentos
  WHERE entidade_id = p_entidade_id
    AND org_id = public.get_current_org_id();
$$;

GRANT EXECUTE ON FUNCTION public.conta_corrente_saldo(uuid) TO authenticated;

-- ============================================================
-- Triggers: postar movimentos a partir de cobranças e recibos
-- ============================================================

-- Cobrança emitida → débito na conta do destinatário.
-- Cobrança anulada após emissão → crédito de estorno.
CREATE OR REPLACE FUNCTION public.fn_cobranca_posta_movimento()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.estado = 'emitida' THEN
      INSERT INTO public.conta_movimentos
        (org_id, entidade_id, tipo, valor, origem, cobranca_id, contrato_id, descricao)
      VALUES
        (NEW.org_id, NEW.destinatario_id, 'debito', NEW.valor_total, 'cobranca',
         NEW.id, NEW.contrato_id, COALESCE(NEW.descricao, 'Cobrança de contrato'));
    END IF;

  ELSIF TG_OP = 'UPDATE' THEN
    IF OLD.estado = 'pendente' AND NEW.estado = 'emitida' THEN
      INSERT INTO public.conta_movimentos
        (org_id, entidade_id, tipo, valor, origem, cobranca_id, contrato_id, descricao)
      VALUES
        (NEW.org_id, NEW.destinatario_id, 'debito', NEW.valor_total, 'cobranca',
         NEW.id, NEW.contrato_id, COALESCE(NEW.descricao, 'Cobrança de contrato'));

    ELSIF OLD.estado IN ('emitida','paga') AND NEW.estado = 'anulada' THEN
      INSERT INTO public.conta_movimentos
        (org_id, entidade_id, tipo, valor, origem, cobranca_id, contrato_id, descricao)
      VALUES
        (NEW.org_id, NEW.destinatario_id, 'credito', NEW.valor_total, 'cobranca',
         NEW.id, NEW.contrato_id, 'Estorno de cobrança anulada');
    END IF;
  END IF;

  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_cobranca_posta_movimento ON public.contrato_cobrancas;
CREATE TRIGGER trg_cobranca_posta_movimento
  AFTER INSERT OR UPDATE OF estado ON public.contrato_cobrancas
  FOR EACH ROW EXECUTE FUNCTION public.fn_cobranca_posta_movimento();

-- Recibo criado → crédito. Recibo anulado → débito de estorno.
CREATE OR REPLACE FUNCTION public.fn_recibo_posta_movimento()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.estado = 'ativo' THEN
      INSERT INTO public.conta_movimentos
        (org_id, entidade_id, tipo, valor, origem, recibo_id, contrato_id, descricao)
      VALUES
        (NEW.org_id, NEW.entidade_id, 'credito', NEW.valor, 'recibo',
         NEW.id, NEW.contrato_id, COALESCE('Recibo nº ' || NEW.codigo, 'Recibo'));
    END IF;

  ELSIF TG_OP = 'UPDATE' AND OLD.estado = 'ativo' AND NEW.estado = 'anulado' THEN
    INSERT INTO public.conta_movimentos
      (org_id, entidade_id, tipo, valor, origem, recibo_id, contrato_id, descricao)
    VALUES
      (NEW.org_id, NEW.entidade_id, 'debito', NEW.valor, 'recibo',
       NEW.id, NEW.contrato_id, 'Estorno de recibo anulado');
  END IF;

  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_recibo_posta_movimento ON public.recibos;
CREATE TRIGGER trg_recibo_posta_movimento
  AFTER INSERT OR UPDATE OF estado ON public.recibos
  FOR EACH ROW EXECUTE FUNCTION public.fn_recibo_posta_movimento();

-- updated_at dos recibos
CREATE OR REPLACE FUNCTION public.touch_recibos_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at := now(); RETURN NEW; END;
$$;
DROP TRIGGER IF EXISTS trg_recibos_updated_at ON public.recibos;
CREATE TRIGGER trg_recibos_updated_at
  BEFORE UPDATE ON public.recibos
  FOR EACH ROW EXECUTE FUNCTION public.touch_recibos_updated_at();

-- ============================================================
-- RLS
-- ============================================================
ALTER TABLE public.recibos          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conta_movimentos ENABLE ROW LEVEL SECURITY;

-- recibos
DROP POLICY IF EXISTS "mt_recibos_select" ON public.recibos;
DROP POLICY IF EXISTS "mt_recibos_insert" ON public.recibos;
DROP POLICY IF EXISTS "mt_recibos_update" ON public.recibos;

CREATE POLICY "mt_recibos_select" ON public.recibos
  FOR SELECT TO authenticated
  USING (org_id = get_current_org_id() AND has_renting_faturacao_access());
CREATE POLICY "mt_recibos_insert" ON public.recibos
  FOR INSERT TO authenticated
  WITH CHECK (org_id = get_current_org_id() AND has_renting_faturacao_access());
CREATE POLICY "mt_recibos_update" ON public.recibos
  FOR UPDATE TO authenticated
  USING (org_id = get_current_org_id() AND has_renting_faturacao_access());
-- sem DELETE: recibos anulam-se (estado), não se apagam

-- conta_movimentos — livro razão: leitura e inserção (via triggers); sem delete
DROP POLICY IF EXISTS "mt_conta_movimentos_select" ON public.conta_movimentos;
DROP POLICY IF EXISTS "mt_conta_movimentos_insert" ON public.conta_movimentos;
DROP POLICY IF EXISTS "mt_conta_movimentos_update" ON public.conta_movimentos;

CREATE POLICY "mt_conta_movimentos_select" ON public.conta_movimentos
  FOR SELECT TO authenticated
  USING (org_id = get_current_org_id() AND has_renting_faturacao_access());
CREATE POLICY "mt_conta_movimentos_insert" ON public.conta_movimentos
  FOR INSERT TO authenticated
  WITH CHECK (org_id = get_current_org_id() AND has_renting_faturacao_access());
-- update apenas para marcar sincronização com o Primavera
CREATE POLICY "mt_conta_movimentos_update" ON public.conta_movimentos
  FOR UPDATE TO authenticated
  USING (org_id = get_current_org_id() AND has_renting_faturacao_access());

COMMENT ON TABLE public.conta_movimentos IS
  'Livro razão da conta-corrente (append-only). Saldo = Σ débitos − Σ créditos. '
  'Postado automaticamente por triggers de contrato_cobrancas e recibos.';
COMMENT ON TABLE public.recibos IS
  'Pagamentos recebidos. Cada recibo ativo gera um crédito na conta-corrente da entidade.';
COMMENT ON FUNCTION public.conta_corrente_saldo(uuid) IS
  'Saldo da conta-corrente: positivo = a entidade deve; negativo = crédito a favor dela.';
